# Nome do Workflow
name: Hack10 Pipeline

# Evento que irá acionar a pipeline
on: 
  push:
    branches:
      - pipedev

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install Requirements
        run:  pip install flask flask-wtf flask-cors PyMySQL cryptography gunicorn

      - name: Docker Login
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          ARTIFACT_REGISTRY:  ${{ secrets.ARTIFACT_REGISTRY}}
        run: | 
          echo '${{ secrets.GOOGLE_CREDENTIALS }}' > key.json
          cat key.json | docker login -u _json_key --password-stdin ${{ secrets.ARTIFACT_REGISTRY }}

      - name: Build Image & Push
        env: 
          ARTIFACT_REGISTRY_REPO: ${{ secrets.ARTIFACT_REGISTRY_REPO }}
          CLOUD_SQL_USERNAME: ${{ secrets.CLOUD_SQL_USERNAME }}
          CLOUD_SQL_PASSWORD: ${{ secrets.CLOUD_SQL_PASSWORD }}
          CLOUD_SQL_DATABASE_NAME: ${{ secrets.CLOUD_SQL_DATABASE_NAME }}
          DB_LOCAL_HOST: ${{ secrets.DB_LOCAL_HOST }}
          CLOUD_SQL_CONNECTION_NAME: ${{ secrets.CLOUD_SQL_CONNECTION_NAME }}
          echo '${{ secrets.CLOUD_SQL_DATABASE_NAME }}
        run: | 
          docker build -t ${{ secrets.ARTIFACT_REGISTRY_REPO }}/myapp:latest .
          docker push ${{ secrets.ARTIFACT_REGISTRY_REPO }}/myapp:latest        


  DeployProd:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Auth GCP Cloud Run
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Deploy to Cloud
        id: cloudrun
        env: 
          ARTIFACT_REGISTRY_REPO: ${{ secrets.ARTIFACT_REGISTRY_REPO }}
        uses: 'google-github-actions/deploy-cloudrun@v0'
        with:
          service: 'hack10-cloud-run'
          image: ${{ secrets.ARTIFACT_REGISTRY_REPO }}/myapp:latest

      - name: Prod Test
        run: 'curl "${{ steps.cloudrun.outputs.url }}"'


